import type { Category, Collection, HomepageContent, Media, Offer, Product, Review } from "./types";

/*
 * Development seed. Images are procedurally generated placeholders
 * (scripts/generate-textures.mjs); replace with real photography in the CMS.
 */

const img = (name: string, alt: string): Media => ({
  src: `/media/${name}.webp`,
  macro: `/media/${name}-macro.webp`,
  alt,
  width: 1200,
  height: 1500,
});

export const categories: Category[] = [
  { id: "c-fabrics", slug: "fabrics", name: "الأقمشة", description: "أقمشة رجالية مختارة لكل موسم ومناسبة.", sortOrder: 1 },
  { id: "c-summer", slug: "summer-fabrics", parentId: "c-fabrics", name: "أقمشة صيفية", description: "خامات خفيفة تتنفس مع حرارة الصيف.", image: img("summer-ivory", "قماش صيفي عاجي"), sortOrder: 1 },
  { id: "c-winter", slug: "winter-fabrics", parentId: "c-fabrics", name: "أقمشة شتوية", description: "صوف ومزائج دافئة بحضور ثقيل.", image: img("winter-charcoal", "قماش شتوي فحمي"), sortOrder: 2 },
  { id: "c-japanese", slug: "japanese-fabrics", parentId: "c-fabrics", name: "أقمشة يابانية", description: "نسيج ياباني دقيق بلمعة هادئة.", image: img("japanese-white", "قماش ياباني أبيض"), sortOrder: 3 },
  { id: "c-cotton", slug: "cotton-fabrics", parentId: "c-fabrics", name: "أقمشة قطنية", description: "قطن طبيعي ناعم للاستخدام اليومي.", image: img("cotton-sand", "قماش قطني رملي"), sortOrder: 4 },
  { id: "c-luxury", slug: "luxury-fabrics", parentId: "c-fabrics", name: "أقمشة فاخرة", description: "خامات نادرة للمناسبات الخاصة.", image: img("luxury-navy", "قماش فاخر كحلي"), sortOrder: 5 },
  { id: "c-daily", slug: "daily-fabrics", parentId: "c-fabrics", name: "أقمشة يومية", description: "عملية وأنيقة لكل يوم.", image: img("daily-grey", "قماش يومي رمادي"), sortOrder: 6 },
  { id: "c-thobes", slug: "thobes", name: "الثياب", description: "ثياب جاهزة بقصّات مدروسة.", sortOrder: 2 },
  { id: "c-boxes", slug: "boxes", name: "البوكسات", description: "بوكسات هدايا مختارة.", sortOrder: 4 },
  { id: "c-acc", slug: "accessories", name: "مستلزمات الإطلالة", description: "كل ما يكمل حضورك.", sortOrder: 5 },
  { id: "c-shemagh", slug: "shemagh", parentId: "c-acc", name: "شماغ", description: "", sortOrder: 1 },
  { id: "c-agal", slug: "agal", parentId: "c-acc", name: "عقال", description: "", sortOrder: 2 },
  { id: "c-sedairi", slug: "sedairi", parentId: "c-acc", name: "سديري", description: "", sortOrder: 3 },
  { id: "c-misbaha", slug: "misbaha", parentId: "c-acc", name: "سبحة", description: "", sortOrder: 4 },
  { id: "c-perfumes", slug: "perfumes", parentId: "c-acc", name: "عطور", description: "", sortOrder: 5 },
  { id: "c-oud", slug: "oud-bakhoor", parentId: "c-acc", name: "عود وبخور", description: "", sortOrder: 6 },
  { id: "c-gifts", slug: "gifts", parentId: "c-acc", name: "هدايا", description: "", sortOrder: 7 },
];

const fabric = (o: Partial<Product> & Pick<Product, "id" | "slug" | "name" | "shortDescription" | "price" | "categoryIds" | "images" | "fabric">): Product => ({
  sku: o.id.toUpperCase(),
  description: o.shortDescription,
  unit: "meter",
  rating: { average: 4.8, count: 120 },
  tags: [],
  inventory: 40,
  createdAt: "2026-09-01T00:00:00.000Z",
  ...o,
});

const item = (o: Partial<Product> & Pick<Product, "id" | "slug" | "name" | "shortDescription" | "price" | "categoryIds" | "images">): Product => ({
  sku: o.id.toUpperCase(),
  description: o.shortDescription,
  unit: "piece",
  rating: { average: 4.8, count: 40 },
  tags: [],
  inventory: 25,
  createdAt: "2026-08-15T00:00:00.000Z",
  ...o,
});

export const products: Product[] = [
  fabric({
    id: "p-ivory-zephyr",
    slug: "ivory-zephyr-summer",
    name: "زفير عاجي",
    shortDescription: "قماش صيفي خفيف بلون عاجي دافئ.",
    description: "نسيج صيفي يجمع بين الخفة والانسدال الهادئ. يمرّ الهواء خلاله بسهولة ويحتفظ بشكله طوال اليوم.",
    price: 18900,
    compareAtPrice: 22900,
    categoryIds: ["c-fabrics", "c-summer"],
    images: [img("summer-ivory", "قماش زفير عاجي منسدل")],
    fabric: { type: "تويل خفيف", material: "بوليستر وفسكوز", texture: "ناعم بانسدال", season: "صيفي", color: "عاجي", width: "150 سم", origin: "كوريا" },
    rating: { average: 4.9, count: 214 },
    isBestSeller: true,
    tags: ["صيفي", "أبيض", "عاجي"],
  }),
  fabric({
    id: "p-kyoto-white",
    createdAt: "2026-09-20T00:00:00.000Z",
    slug: "kyoto-japanese-white",
    name: "كيوتو الأبيض",
    shortDescription: "قماش ياباني بلمعة هادئة وملمس مصقول.",
    description: "نسيج ياباني بكثافة خيوط عالية يمنح الثوب بياضًا نقيًا ولمعة خفيفة لا تُرى إلا تحت الضوء.",
    price: 34500,
    categoryIds: ["c-fabrics", "c-japanese", "c-luxury", "c-summer"],
    images: [img("japanese-white", "قماش كيوتو الياباني الأبيض")],
    fabric: { type: "ساتان ياباني", material: "بوليستر ياباني عالي الكثافة", texture: "مصقول بلمعة هادئة", season: "كل المواسم", color: "أبيض ثلجي", width: "152 سم", origin: "اليابان" },
    rating: { average: 5, count: 168 },
    isBestSeller: true,
    tags: ["ياباني", "أبيض", "فاخر", "يابانية"],
  }),
  fabric({
    id: "p-charcoal-wool",
    slug: "charcoal-winter-wool",
    name: "صوف فحمي",
    shortDescription: "مزيج صوف شتوي بحضور ثقيل ودافئ.",
    description: "قماش شتوي من مزيج الصوف يمنح دفئًا متوازنًا دون ثقل مزعج، بلون فحمي عميق.",
    price: 42000,
    compareAtPrice: 48000,
    categoryIds: ["c-fabrics", "c-winter", "c-luxury"],
    images: [img("winter-charcoal", "قماش صوف شتوي فحمي")],
    fabric: { type: "صوف ممزوج", material: "صوف 60% وبوليستر 40%", texture: "دافئ ومتماسك", season: "شتوي", color: "فحمي", width: "150 سم", origin: "إيطاليا" },
    rating: { average: 4.8, count: 96 },
    isBestSeller: true,
    tags: ["شتوي", "صوف", "رمادي"],
  }),
  fabric({
    id: "p-sand-cotton",
    slug: "sand-pure-cotton",
    name: "قطن رملي",
    shortDescription: "قطن طبيعي بلون رملي هادئ.",
    description: "قطن طبيعي ناعم على البشرة، مثالي للاستخدام اليومي في الأجواء الحارة.",
    price: 15900,
    categoryIds: ["c-fabrics", "c-cotton", "c-daily", "c-summer"],
    images: [img("cotton-sand", "قماش قطني رملي")],
    fabric: { type: "قطن مغزول", material: "قطن 100%", texture: "طبيعي ومريح", season: "صيفي", color: "رملي", width: "145 سم", origin: "مصر" },
    rating: { average: 4.7, count: 132 },
    isBestSeller: true,
    tags: ["قطن", "يومي", "بيج"],
  }),
  fabric({
    id: "p-midnight-navy",
    slug: "midnight-navy-luxury",
    name: "كحلي منتصف الليل",
    shortDescription: "قماش فاخر بلون كحلي عميق.",
    description: "خامة فاخرة للمناسبات المسائية، بلون كحلي يقترب من الأسود في الإضاءة الخافتة.",
    price: 38900,
    categoryIds: ["c-fabrics", "c-luxury", "c-winter"],
    images: [img("luxury-navy", "قماش كحلي فاخر")],
    fabric: { type: "تويل فاخر", material: "صوف ممزوج", texture: "كثيف وناعم", season: "شتوي", color: "كحلي", width: "150 سم", origin: "إيطاليا" },
    rating: { average: 4.9, count: 71 },
  }),
  fabric({
    id: "p-stone-daily",
    slug: "stone-grey-daily",
    name: "رمادي حجري",
    shortDescription: "قماش يومي عملي بلون رمادي متوازن.",
    description: "قماش يومي يقاوم التجعد ويحافظ على أناقته من الصباح حتى المساء.",
    price: 13900,
    compareAtPrice: 16900,
    categoryIds: ["c-fabrics", "c-daily"],
    images: [img("daily-grey", "قماش رمادي يومي")],
    fabric: { type: "بوبلين", material: "بوليستر وقطن", texture: "عملي ومقاوم للتجعد", season: "كل المواسم", color: "رمادي حجري", width: "150 سم" },
    rating: { average: 4.6, count: 88 },
  }),
  fabric({
    id: "p-oud-brown",
    slug: "oud-brown-winter",
    name: "بني العود",
    shortDescription: "قماش شتوي بلون بني دافئ.",
    description: "لون مستوحى من خشب العود، بنسيج شتوي متماسك يناسب أمسيات الشتاء.",
    price: 36900,
    categoryIds: ["c-fabrics", "c-winter"],
    images: [img("winter-brown", "قماش شتوي بني")],
    fabric: { type: "صوف ممزوج", material: "صوف 50% وفسكوز 50%", texture: "دافئ بملمس مخملي", season: "شتوي", color: "بني", width: "150 سم" },
    rating: { average: 4.8, count: 54 },
  }),
  fabric({
    id: "p-noir-silk",
    createdAt: "2026-10-01T00:00:00.000Z",
    slug: "noir-silk-touch",
    name: "نوار",
    shortDescription: "قماش أسود بلمسة حريرية.",
    description: "أسود عميق بلمسة حريرية وانسدال انسيابي. حضور هادئ لا يحتاج إلى كلام.",
    price: 45900,
    categoryIds: ["c-fabrics", "c-luxury"],
    images: [img("black-silk", "قماش أسود بلمسة حريرية")],
    fabric: { type: "ساتان", material: "فسكوز وحرير", texture: "حريري انسيابي", season: "كل المواسم", color: "أسود", width: "140 سم", origin: "اليابان" },
    rating: { average: 5, count: 39 },
    tags: ["أسود", "حرير", "ياباني"],
  }),
  // Accessories, thobes and boxes
  item({
    id: "p-shemagh-red-classic",
    slug: "classic-red-shemagh",
    name: "شماغ أحمر كلاسيكي",
    shortDescription: "قطن مصري مغزول بنقشة حمراء ثابتة.",
    description: "شماغ من القطن المصري بنقشة حمراء عميقة لا تبهت، وحواف مخيطة بإتقان.",
    price: 32900,
    compareAtPrice: 37900,
    categoryIds: ["c-acc", "c-shemagh"],
    images: [img("shemagh-red", "شماغ أحمر كلاسيكي")],
    attributes: { color: "أحمر", season: "كل المواسم", origin: "إنجلترا" },
    rating: { average: 4.9, count: 302 },
    isBestSeller: true,
    tags: ["شماغ", "أحمر", "قطن"],
  }),
  item({
    id: "p-ghutra-white",
    slug: "white-ghutra-summer",
    name: "غترة بيضاء صيفية",
    shortDescription: "غترة خفيفة بنسيج ناعم للصيف.",
    description: "غترة بيضاء من قطن خفيف، تحافظ على شكلها وتتنفس في الحر.",
    price: 18900,
    categoryIds: ["c-acc", "c-shemagh"],
    images: [img("ghutra-white", "غترة بيضاء صيفية")],
    attributes: { color: "أبيض", season: "صيفي" },
    rating: { average: 4.7, count: 118 },
    tags: ["غترة", "شماغ", "أبيض", "صيفي"],
  }),
  item({
    id: "p-agal-black",
    slug: "black-agal-classic",
    name: "عقال أسود مرعز",
    shortDescription: "عقال مرعز بلفّ يدوي متقن.",
    description: "عقال أسود من المرعز، ملفوف يدويًا بثبات يحافظ على شكله سنوات.",
    price: 14900,
    categoryIds: ["c-acc", "c-agal"],
    images: [img("black-silk", "عقال أسود مرعز")],
    attributes: { color: "أسود" },
    rating: { average: 4.8, count: 87 },
    tags: ["عقال", "أسود"],
  }),
  item({
    id: "p-sedairi-camel",
    slug: "camel-wool-sedairi",
    name: "سديري صوف جملي",
    shortDescription: "سديري شتوي بلون جملي دافئ.",
    description: "سديري من الصوف الممزوج، بقصة مستقيمة تجلس على الثوب بدون انتفاخ.",
    price: 27900,
    categoryIds: ["c-acc", "c-sedairi"],
    images: [img("sedairi-camel", "سديري صوف جملي")],
    attributes: { color: "جملي", season: "شتوي" },
    rating: { average: 4.8, count: 46 },
    tags: ["سديري", "شتوي", "صوف"],
  }),
  item({
    id: "p-misbaha-kuk",
    slug: "kuk-wood-misbaha",
    name: "سبحة كوك",
    shortDescription: "33 حبة كوك طبيعي بشرابة سوداء.",
    description: "سبحة من خشب الكوك الطبيعي، تزداد لمعة مع الاستخدام.",
    price: 22900,
    categoryIds: ["c-acc", "c-misbaha", "c-gifts"],
    images: [img("winter-brown", "سبحة كوك طبيعي")],
    attributes: { color: "بني" },
    rating: { average: 4.9, count: 64 },
    inventory: 0,
    tags: ["سبحة", "هدية"],
  }),
  item({
    id: "p-oud-cambodi",
    slug: "cambodian-oud-chips",
    name: "عود كمبودي",
    shortDescription: "قطع عود كمبودي بثبات طويل، 25 جرامًا.",
    description: "عود كمبودي مختار، دخانه هادئ ورائحته تبقى في المجلس والثياب.",
    price: 49900,
    categoryIds: ["c-acc", "c-oud", "c-gifts"],
    images: [img("winter-brown", "عود كمبودي")],
    attributes: { origin: "كمبوديا" },
    rating: { average: 5, count: 41 },
    unit: "piece",
    tags: ["عود", "بخور", "هدية"],
  }),
  item({
    id: "p-perfume-majlis",
    slug: "majlis-eau-de-parfum",
    name: "عطر المجلس",
    shortDescription: "عطر خشبي بلمسة عود وعنبر، 100 مل.",
    description: "عطر خشبي دافئ يفتتح بالزعفران ويستقر على العود والعنبر.",
    price: 39900,
    compareAtPrice: 44900,
    categoryIds: ["c-acc", "c-perfumes", "c-gifts"],
    images: [img("box-backdrop", "عطر المجلس")],
    rating: { average: 4.8, count: 129 },
    tags: ["عطر", "عود", "هدية"],
  }),
  item({
    id: "p-thobe-ivory",
    slug: "ivory-tailored-thobe",
    name: "ثوب عاجي مفصّل",
    shortDescription: "ثوب جاهز من قماش زفير العاجي.",
    description: "ثوب بقصة سعودية كلاسيكية من قماش زفير العاجي، بياقة مرتبة وأزرار مخفية.",
    price: 54900,
    categoryIds: ["c-thobes"],
    images: [img("summer-ivory", "ثوب عاجي مفصّل")],
    attributes: { color: "عاجي", season: "صيفي" },
    rating: { average: 4.8, count: 77 },
    tags: ["ثوب", "صيفي"],
  }),
  item({
    id: "p-thobe-japanese",
    slug: "japanese-white-thobe",
    name: "ثوب ياباني أبيض",
    shortDescription: "ثوب جاهز من قماش كيوتو الياباني.",
    description: "ثوب من قماش كيوتو الياباني بلمعة هادئة، للمناسبات والأعياد.",
    price: 69900,
    categoryIds: ["c-thobes"],
    images: [img("japanese-white", "ثوب ياباني أبيض")],
    attributes: { color: "أبيض", season: "كل المواسم", origin: "اليابان" },
    rating: { average: 4.9, count: 58 },
    tags: ["ثوب", "ياباني"],
  }),
  item({
    id: "p-box-majlis",
    slug: "majlis-gift-box",
    name: "بوكس المجلس",
    shortDescription: "قماش ياباني، شماغ، عطر، وعود.",
    description: "بوكس هدية متكامل في صندوق أسود بخيط ذهبي، مع بطاقة إهداء مكتوبة بخط اليد.",
    price: 129900,
    compareAtPrice: 145600,
    categoryIds: ["c-boxes", "c-gifts"],
    images: [{ src: "/media/box-backdrop.webp", alt: "بوكس المجلس", width: 1600, height: 1600 }],
    rating: { average: 5, count: 33 },
    unit: "set",
    tags: ["بوكس", "هدية"],
  }),
  item({
    id: "p-box-essentials",
    slug: "essentials-gift-box",
    name: "بوكس الأساسيات",
    shortDescription: "قماش قطني، غترة، وسبحة.",
    description: "بداية أنيقة لهدية عملية: قماش قطني وغترة صيفية وسبحة، في صندوق الدار.",
    price: 59900,
    categoryIds: ["c-boxes", "c-gifts"],
    images: [{ src: "/media/box-backdrop.webp", alt: "بوكس الأساسيات", width: 1600, height: 1600 }],
    rating: { average: 4.8, count: 21 },
    unit: "set",
    tags: ["بوكس", "هدية"],
  }),
];

export const collections: Collection[] = [
  { id: "col-summer", slug: "summer", title: "الصيفي", subtitle: "خفة تتنفس", href: "/categories/summer-fabrics", image: img("summer-ivory", "مجموعة الأقمشة الصيفية"), sortOrder: 1 },
  { id: "col-winter", slug: "winter", title: "الشتوي", subtitle: "دفء بحضور", href: "/categories/winter-fabrics", image: img("winter-charcoal", "مجموعة الأقمشة الشتوية"), sortOrder: 2 },
  { id: "col-japanese", slug: "japanese", title: "الياباني", subtitle: "دقة النسيج", href: "/categories/japanese-fabrics", image: img("japanese-white", "مجموعة الأقمشة اليابانية"), sortOrder: 3 },
  { id: "col-cotton", slug: "cotton", title: "القطني", subtitle: "راحة طبيعية", href: "/categories/cotton-fabrics", image: img("cotton-sand", "مجموعة الأقمشة القطنية"), sortOrder: 4 },
  { id: "col-best", slug: "best-sellers", title: "الأكثر مبيعًا", subtitle: "اختيار عملائنا", href: "/categories/fabrics?sort=best", image: img("luxury-navy", "الأقمشة الأكثر مبيعًا"), sortOrder: 5 },
];

export const offers: Offer[] = [
  { id: "o-summer-pair", label: "بكج الصيف", title: "قطعتان من الصيفي", description: "قماشان صيفيان من اختيارك بقيمة أفضل.", href: "/categories/summer-fabrics", price: 32900, compareAtPrice: 37800, image: img("summer-ivory", "بكج قماشين صيفيين") },
  { id: "o-winter-set", label: "إطلالة الشتاء", title: "قماش شتوي وشماغ", description: "قماش صوف مع شماغ شتوي مطابق.", href: "/categories/winter-fabrics", price: 49900, compareAtPrice: 57500, image: img("winter-brown", "بكج إطلالة الشتاء") },
  { id: "o-japanese-trio", label: "الثلاثية اليابانية", title: "ثلاثة أقمشة يابانية", description: "للخزانة الكاملة لموسم كامل.", href: "/categories/japanese-fabrics", price: 89900, compareAtPrice: 103500, image: img("japanese-white", "ثلاثة أقمشة يابانية") },
];

export const reviews: Review[] = [
  { id: "r1", featured: true, productId: "p-kyoto-white", author: "عبدالله الحربي", city: "الرياض", rating: 5, body: "القماش الياباني أفضل مما توقعت. اللمعة هادئة والخياط أثنى على جودته.", createdAt: "2026-08-12", verified: true },
  { id: "r2", featured: true, author: "فيصل القحطاني", city: "جدة", rating: 5, body: "التغليف وحده يكفي ليعطيك انطباع الفخامة. والتوصيل كان في يومين.", createdAt: "2026-08-30", verified: true },
  { id: "r3", featured: true, author: "سلطان العتيبي", city: "الدمام", rating: 5, body: "طلبت بوكس هدية لوالدي، وكانت التفاصيل مرتبة بعناية. تجربة تستحق.", createdAt: "2026-09-14", verified: true },
  { id: "r5", productId: "p-kyoto-white", author: "نواف الدوسري", city: "الرياض", rating: 5, body: "فصّلت منه ثوب العيد. البياض ثابت بعد الغسيل، والقماش لا يتجعد بسهولة.", createdAt: "2026-09-02", verified: true },
  { id: "r6", productId: "p-kyoto-white", author: "خالد المطيري", city: "الكويت", rating: 4, body: "جودة عالية. تمنيت لو كان العرض أكبر قليلًا لأن طولي 190.", createdAt: "2026-09-28", verified: true },
  { id: "r7", productId: "p-ivory-zephyr", author: "تركي الغامدي", city: "جدة", rating: 5, body: "خفيف جدًا ومناسب لرطوبة جدة. لونه العاجي أجمل من الصور.", createdAt: "2026-07-19", verified: true },
  { id: "r8", productId: "p-shemagh-red-classic", author: "بندر الشمري", city: "حائل", rating: 5, body: "النقشة ثابتة والقماش يمسك الكوية. أفضل شماغ اشتريته أونلاين.", createdAt: "2026-09-10", verified: true },
  { id: "r4", featured: true, productId: "p-charcoal-wool", author: "ماجد الشهري", city: "أبها", rating: 4, body: "الصوف الفحمي دافئ وثقيل بالشكل الصحيح. سأعود للموسم القادم.", createdAt: "2026-09-21", verified: true },
];

export const homepage: HomepageContent = {
  hero: {
    eyebrow: "دار أقمشة رجالية سعودية",
    title: "الشيوخ",
    tagline: "فخامة تلبسها.",
    body: "أقمشة رجالية مختارة بعناية، لتصنع إطلالة تليق بك.",
    primaryCta: { label: "اكتشف الأقمشة", href: "/categories/fabrics" },
    secondaryCta: { label: "تسوق الآن", href: "/categories/summer-fabrics" },
    image: { src: "/media/hero-drape.webp", alt: "قماش رجالي أسود فاخر منسدل", width: 2400, height: 1500 },
  },
  fabricDetail: {
    title: "تفاصيل تحكي الفخامة",
    body: "اقترب من القماش كما تقترب منه في الدار. مرّر المؤشر على الصورة لترى النسيج خيطًا خيطًا.",
    image: { src: "/media/japanese-white-macro.webp", alt: "صورة مقرّبة لنسيج قماش ياباني أبيض", width: 1200, height: 1200 },
    points: [
      { label: "النسيج", text: "خيوط متقاربة بكثافة عالية تمنح سطحًا متساويًا." },
      { label: "الخامة", text: "ألياف مختارة تحافظ على البياض والانسدال." },
      { label: "الملمس", text: "ناعم ومصقول، بارد على البشرة في الصيف." },
      { label: "اللون", text: "أبيض ثلجي ثابت لا يصفرّ مع الغسيل." },
    ],
  },
  boxes: {
    title: "بوكسات الشيوخ",
    subtitle: "هديتك تبدأ من التفاصيل.",
    body: "قماش مختار، وشماغ، وعطر، ولمسة عود. في صندوق يُفتح على مهل.",
    href: "/categories/boxes",
    priceFrom: 59900,
  },
};
